id: P004559
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W21026
  title: བཀྲ་ཤིས་དཔལ་གྱི་རྣམ་ཐར
  author: ''
  volumes:
    d8e19ca602cb47318aec74cd8bd18bec:
      image_group_id: I1KG972
      title: ''
      volume_number: 1
      total_pages: 482
      base_file: v001.txt
