id: I139BF385
legacy_id: P004559
ocr_import_info:
  bdrc_scan_id: W21026
  source: bdrc
  ocr_info:
    timestamp: '2020-03-29T19:35:15'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-01T13:53:55.304961+00:00'
last_modified: 2022-09-01 21:54:11.327865
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W21026
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW21026
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: བཀྲ་ཤིས་དཔལ་གྱི་རྣམ་ཐར།
  author: སྟག་ལུང་ཞབས་དྲུང་ངག་དབང་རྣམ་རྒྱལ།
statistics:
  ocr_word_mean_confidence_index: 0.7140836477098403
  ocr_word_median_confidence_index: 0.7799999713897705
quality: null
bases:
  I1KG972:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG972
      total_pages: 482
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG972.txt
    statistics:
      ocr_word_median_confidence_index: 0.7799999713897705
      ocr_word_mean_confidence_index: 0.7140836477098403
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
